[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nftmarketplace = "EKReNxVoonN5sRAVgvNQiMWFfvkyRYSqWnNoYgAUaQRW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"
